[theme]
base = "light"
primaryColor = "#5ba632"
backgroundColor = "#f7f9f7"
secondaryBackgroundColor = "#ffffff"
textColor = "#1c2b1c"
font = "sans serif"
 
[server]
headless = true
enableCORS = false

```
